//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_egitim
    {
        public short ID { get; set; }
        public string BASLIK { get; set; }
        public string ALT_BASLIK { get; set; }
        public string ACIKLAMA { get; set; }
        public string GNOT { get; set; }
        public string TARIH { get; set; }
    }
}
